### ISSUE TITLE
Add support for HTTP/2

### ISSUE THREAD

**Issue by SethMichaelLarson** [SethMichaelLarson/stormhttp#54]
HTTP 2 would be quite a large undertaking but is the future of the web. Adding support will almost certainly require a re-working of the existing architecture of this module for the better. Any help with this task would be greatly appreciated.

**Comment by SethMichaelLarson** [comment]
HTTP/2 support is going well, although I suspect an issue with RFC 7541 (HPACK) examples. See more here: http://stackoverflow.com/questions/39621953/are-the-string-encoding-examples-for-rfc-7541-hpack-incorrect

**Comment by SethMichaelLarson** [comment]
HTTP/2 support still coming along strong. Now working on the parser for HTTP/2 frames. Will need to also work on NPN/ALPN as well as almost all browsers disallow the use for HTTP/2 without ALPN.

**Comment by Lukasa** [comment]
This is admittedly a bit late in the game, but you could probably have saved 8 days of work by just using [hyper-h2](http://python-hyper.org/h2/) instead. Still, good work!

**Comment by SethMichaelLarson** [comment]
@Lukasa Dang, nice find! It has been fun implementing it myself but I'll use both my own and their implementation and do some testing. If there's is faster I'll immediately replace mine with theirs. Thanks again!

**Comment by Lukasa** [comment]
No problem! Let me know if you find low-hanging performance fruit floating around. I suspect that the perf will be a bit slower: while we knocked out all the obvious perf problems hyper-h2 is more general and focused on correctness, which has a tendency to slow things down. ;)

**Comment by SethMichaelLarson** [comment]
@Lukasa Haha that's what I'm aiming for with this project, fast and "technically" correct but not correctness focused. I'll share the benchmarks with you once I get a Hyper2Protocol and Http2Protocol complete.

**Comment by SethMichaelLarson** [comment]
@Lukasa I added basic HTTP/2 support using hyper-h2, feel free to take a look if you'd like. It's under stormhttp/proto .

**Comment by Lukasa** [comment]
Cool, so that's a really good start! I have some feedback on what you've written so far, and what is yet to do:

1. You're not tolerating RST_STREAM or GOAWAY frames yet, which fire other events. Really, the minimal set of events you need to be able to handle to get a good experience are:

    - [X] RequestReceived
    - [X] Data Received
    - [ ] Window Updated
    - [ ] Stream Reset
    - [ ] Connection Terminated

    Ideally you'd also want to handle Trailers Received, but you can let that one pass in the first instance.
2. The other thing that list hints at: you're not handling flow control. This means that, with the hyper-h2 implementation you have right now, eventually a client will exhaust the connection flow control window and be unable to send more bytes. Resolving this is a pain in the neck, and I'm in the middle of writing code for hyper-h2 that will automate some of this, but for now the simplest thing to do is every time `DataReceived` fires, to call `H2Connection.increment_flow_control_window` twice with the value of `event.flow_controlled_length`, once with `stream_id=event.stream_id`, and once with `stream_id=0`. That will ensure you never run out of window, even though it is fairly inefficient.
3. You're working a lot with headers as unicode strings. It's not clear to me that you want to do that though. hyper-h2 can totally tolerate headers as bytes, and it can even return them to you if you construct your `H2Connection` object with `header_encoding=False`.

Otherwise, this is looking really good so far!

**Comment by SethMichaelLarson** [comment]
@Lukasa Ah! Being able to get headers as bytes is a big thing! That's the data format that this library works with, bytes, because in the end HTTP is a "byte" protocol even if it's called a "text" protocol. And I was not aware that window size was not auto-magically handled, I'll add handling for that as well. Thanks for the comments!

**Comment by Lukasa** [comment]
Automagically handling window size isn't a great plan because applications should be able to ensure that they don't buffer a gazillion bytes if they don't want to. Twisted deploys this to great effect, only opening the window when it has delivered data to the application, ensuring that it has a strictly bounded memory commitment.

Currently there isn't a faster way to do it, but I'm open to having one. I have no problem with adding a `type` field.

WindowUpdated is handled internally in terms of keeping track of the window, but you should be making sure you don't break flow control windows for your peer. If you try to send data on a stream with insufficient space in its flow control window, h2 will yell at you.

**Comment by SethMichaelLarson** [comment]
@Lukasa Sure, makes sense. I'll make it track the size of the window and comment back.

**Comment by SethMichaelLarson** [comment]
@Lukasa Made the changes you suggested, would this now provide good behavior with the set of Events that I catch and process?

**Comment by Lukasa** [comment]
You're definitely much closer. =)

Your window calculations [here](https://github.com/SethMichaelLarson/stormhttp/blob/master/stormhttp/proto/hyper2.py#L56-L62) seem off to me. When a WindowUpdated event fires for stream `0` that updates the connection flow control window, which is kept track of separately from the windows for each of the streams. The better model might be to use the WindowUpdated events to prompt you to process a stream, and then call [`local_flow_control_window`](http://python-hyper.org/h2/en/stable/api.html#h2.connection.H2Connection.local_flow_control_window) for a given stream which will tell you how many bytes you can *actually* send on that stream, taking the connection window into account.

I should note, as well, that your model of flow control still isn't really right. Partly this is because your server sends bodies back in a single shot: one large DATA frame. That model doesn't really work, for a few reasons. Firstly, some clients will have set SETTINGS_MAX_FRAME_SIZE to smaller than the DATA frame you want to send. hyper-h2 will prevent you from sending a DATA frame that large and will ask you to chunk it up yourself instead. Secondly, most clients will only set the window to a certain size and may not increase it until either a Content-Length header is received or until some of the body has been received. If that size is smaller than the total length of the body, then you'll be unable to ever send it.

Ultimately, you'll need to redraft your approach to sending data to allow you to send data based on the flow control window. This is tricky, but it's a key part of the way HTTP/2 multiplexing functions. Certainly for now however you should be safe enough: these are just things that are worth considering in the future.
